name: Test

on: [push, pull_request]

jobs:
  test:
    name: cargo test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install build deps
        run: >-
          sudo apt-get install -y
          autoconf
          automake
          build-essential
          cmake
          clang
          libc6-dev-i386
          libclang-dev
          llvm-dev
          zlib1g-dev

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Run cargo test
        run: |
          # Try bundled build first
          cargo build --features "bundled,openssl_bundled"
          cargo run --manifest-path examples/hello/Cargo.toml --features "bundled,openssl_bundled" -- 5
          # Now pkg-config build
          sudo apt-get install -y libssl-dev libevent-dev
          cargo clean
          cargo build --no-default-features --features "openssl,pkgconfig,buildtime_bindgen" # pkgconfig, openssl, threading
          cargo run --manifest-path examples/hello/Cargo.toml --no-default-features --features "openssl,pkgconfig,buildtime_bindgen" -- 5

